### ISSUE TITLE
train_1.json集和dev_0.json集应该一一对应吗

### ISSUE THREAD

**Issue by xsthunder** [CLUEbenchmark/FewCLUE#14]
https://github.com/CLUEbenchmark/FewCLUE/blob/f90b637e7af2fedb7f90c084f05f3f5a710a5bb4/baselines/models_keras/ptuning/ptuning_chid.py#L90

看论文理解下来，使用train集和dev集应该一一对应， 即`valid_data += load_data('ready_data/chid/dev_{}.json'.format(train_set_index)) `

> 
since training on small datasets might lead to fluctuating results, we provide multiple training/validation splits to alleviate the issue and make our benchmark more robust

from https://arxiv.org/pdf/2107.07498.pdf

**Comment by brightmart** [comment]
你好， train_i.json和dev_i.json一一对应。如train_0,json和dev_0.json, train_1.json和dev_1.json
